# Generated by Django 4.2.1 on 2023-05-16 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelfs', '0003_book_favourites'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='no_of_rating',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
