# Generated by Django 4.2.1 on 2023-05-16 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelfs', '0004_book_no_of_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='rating',
            field=models.FloatField(),
        ),
    ]
