# Generated by Django 4.2.1 on 2023-05-16 23:07

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shelfs', '0005_alter_book_rating'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Favourites',
            new_name='Favourite',
        ),
    ]
